
[package]
name = "wasmfun"
version = "0.1.0"
edition = "2018"
build = "build.rs"

[dependencies]
bytes = "1.1.0"
nbody = { path = "./nbody" }

[dependencies.wasmer]
version = "2.0.0"
default-features = false
features = ["wat", "default-llvm", "default-universal"]
